### ISSUE TITLE
Ajouter un hover sur les jeux de la page home 

### ISSUE THREAD

**Issue by DeGraciaMathieu** [Lamegaforge/Megasaurus#18]
![image](https://github.com/Lamegaforge/megasaurus-website/assets/11473997/4a37fb26-cb9d-421d-9e2e-37b0f928bbb0)

C'est possible d'avoir un hover semblable aux autres [pages](https://website.megasaurus.test/games) ?

**Comment by clementgalidie** [comment]
https://github.com/Lamegaforge/megasaurus-website/pull/21
